repos:
- repo: https://github.com/ambv/black
  rev: 21.9b0
  hooks:
  - id: black
    args: ["--check",]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910-1
  hooks:
  - id: mypy
- repo: https://github.com/pycqa/isort
  rev: 5.9.3
  hooks:
  - id: isort
    args: ["--check-only", "--profile", "black"]
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
