repos:
- repo: https://github.com/ambv/black
  rev: 21.12b0
  hooks:
  - id: black
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.930
  hooks:
  - id: mypy
    pass_filenames: false
    args: ["."]
    additional_dependencies:
    - nox
    - pytest
    - types-setuptools
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
  - id: isort
    args: ["--profile=black"]
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
